"""empty message

Revision ID: 5aaa98e05074
Revises: 1b08d21a8c1d
Create Date: 2020-11-25 19:35:19.404794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aaa98e05074'
down_revision = '1b08d21a8c1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('room_number', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'room_number')
    # ### end Alembic commands ###
